name: Testing
on: [ push ]
defaults:
  run:
    shell: bash
jobs:
  Testing:
    name: Run tests and generate coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Tests
        run: |
          sudo apt update
          sudo apt install valgrind
          export ASAN_OPTIONS=verify_asan_link_order=0
          chmod +x ./scripts/build.sh
          ./scripts/build.sh -tc
          cd build
          make
          cd ..
      - name: Run Tests tests_PhoneNumber
        run: |
          valgrind --tool=memcheck --leak-check=full ./build/tests_PhoneNumber
          ./build/tests_PhoneNumberAddress
          ./build/tests_PhoneNumberThread
          ./build/tests_PhoneNumberUndefined
      - name: Generate coverage report
        run: |
          chmod +x ./scripts/cov-gen.sh
          ./scripts/cov-gen.sh
      - name: Codecov 
        run: |
      - name: Getting code coverage data
        uses: codecov/codecov-action@v2
        with:
          token: 6241a459-ad22-4286-a183-1a3c2c12ede2
          files: coverage.xml
          